var userdetail,waitRequest={};
var myCaptcha;
var msg={
  'zh_cn':{
    translation:{
      "code8.site.t.5sauclgyc780": "发现作品",
      "code8.site.t.5sauclgyd2o0": "论坛",
      "code8.site.t.5sauclgyda00": "赞助code8",
      "code8.site.t.5sauclgydf40": "创作",
      "code8.site.t.5sauclgydi00": "下载",
      "code8.site.t.5sauclgydl00": "登录/注册",
      "code8.site.t.5sauclgydpg0": "当前页面不存在",
      "code8.site.t.5sauclgydts0": "关于我们：",
      "code8.site.t.5sauclgydxc0": "信息更改",
      "code8.site.t.5sauclgye080": "昵称",
      "code8.site.t.5sauclgye4k0": "个人介绍",
      "code8.site.t.5sauclgye7k0": "支持使用markdown编写",
      "code8.site.t.5sauclgyeas0": "不在新窗口打开页面(访问速度会更快。点更改信息后，按下f5生效)",
      "code8.site.t.5sauclgyedg0": "夜间模式(开启后请刷新)",
      "code8.site.t.5sauclgyehs0": "正在上传中……",
      "code8.site.t.5sauclgyek80": "上传成功",
      "code8.site.t.5sauclgyeow0": "更改信息",
      "code8.site.t.5sauclgyetc0": "旧密码",
      "code8.site.t.5sauclgyewk0": "新密码",
      "code8.site.t.5sauclgyezg0": "更改密码",
      "code8.site.t.5sauclgyf340": "手机号：",
      "code8.site.t.5sauclgyf7c0": "邮箱：",
      "code8.site.t.5sauclgyfbo0": "发布帖子",
      "code8.site.t.5sauclgyffo0": "搜索",
      "code8.site.t.5sauclgyfhs0": "帖子发出",
      "code8.site.t.5sauclgyfjw0": "标题",
      "code8.site.t.5sauclgyfm80": "帖子内容",
      "code8.site.t.5sauclgyfpc0": "发点什么吧",
      "code8.site.t.5sauclgyfrg0": "发布",
      "code8.site.t.5sauclgyftw0": "取消",
      "code8.site.t.5sauclgyfw00": "更多",
      "code8.site.t.5sauclgyfyc0": "用户榜",
      "code8.site.t.5sauclgyg280": "工作室榜",
      "code8.site.t.5sauclgyg4c0": "发送私信",
      "code8.site.t.5sauclgyg6k0": "对方id",
      "code8.site.t.5sauclgyg8g0": "内容",
      "code8.site.t.5sauclgygao0": "发送",
      "code8.site.t.5sauclgyges0": "我的物品",
      "code8.site.t.5sauclgygh00": "金币：",
      "code8.site.t.5sauclgygj40": "金币记录",
      "code8.site.t.5sauclgyglc0": "商店",
      "code8.site.t.5sauclgygo80": "物品信息",
      "code8.site.t.5sauclgygqg0": "小时失效",
      "code8.site.t.5sauclgygsk0": "金币",
      "code8.site.t.5sauclgygv80": "仅可对自己使用",
      "code8.site.t.5sauclgygzc0": "使用",
      "code8.site.t.5sauclgyh1k0": "数量",
      "code8.site.t.5sauclgyh5g0": "购买",
      "code8.site.t.5sauclgyh8w0": "我的工作室：",
      "code8.site.t.5sauclgyiow0": "新建工作室",
      "code8.site.t.5sauclgyiss0": "我的作品：",
      "code8.site.t.5sauclgyiwg0": "新建作品",
      "code8.site.t.5sauclgyiyk0": "删除",
      "code8.site.t.5sauclgyj2w0": "评论",
      "code8.site.t.5sauclgyj740": "作品",
      "code8.site.t.5sauclgyj9c0": "用户",
      "code8.site.t.5sauclgyjbg0": "工作室",
      "code8.site.t.5sauclgyjdg0": "作品名",
      "code8.site.t.5sauclgyjfs0": "作者id",
      "code8.site.t.5sauclgyji00": "用户名",
      "code8.site.t.5sauclgyjk00": "工作室名称",
      "code8.site.t.5sauclgyjnc0": "为你找到",
      "code8.site.t.5sauclgyjps0": "邮箱",
      "code8.site.t.5sauclgyjt00": "邮件验证码(6位)",
      "code8.site.t.5sauclgyjv40": "发送验证码",
      "code8.site.t.5sauclgyjx80": "已有账号？",
      "code8.site.t.5sauclgyjzg0": "登录",
      "code8.site.t.5sauclgyk1g0": "没有账号？",
      "code8.site.t.5sauclgyk3k0": "找回密码",
      "code8.site.t.5sauclgyk5o0": "登录或注册即代表同意",
      "code8.site.t.5sauclgyk7s0": "工作室信息正在加载中",
      "code8.site.t.5sauclgyk9s0": "当前工作室已被封禁，请联系",
      "code8.site.t.5sauclgykc40": "管理员",
      "code8.site.t.5sauclgykec0": "进行申诉",
      "code8.site.t.5sauclgykgg0": "编辑信息",
      "code8.site.t.5sauclgykig0": "加入",
      "code8.site.t.5sauclgykks0": "退出",
      "code8.site.t.5sauclgyko00": "设为主室",
      "code8.site.t.5sauclgykq40": "投稿作品",
      "code8.site.t.5sauclgyks40": "工作室介绍",
      "code8.site.t.5sauclgykuo0": "工作室作品：",
      "code8.site.t.5sauclgykx40": "当前工作室无作品",
      "code8.site.t.5sauclgykz80": "工作室成员：",
      "code8.site.t.5sauclgyl180": "当前工作室无成员",
      "code8.site.t.5sauclgyl380": "请等待",
      "code8.site.t.5sauclgyl5g0": "正在加载中",
      "code8.site.t.5sauclgyl9o0": "工作室名",
      "code8.site.t.5sauclgylc00": "启用密码",
      "code8.site.t.5sauclgyle80": "加入密码",
      "code8.site.t.5sauclgylg80": "禁止任何人加入",
      "code8.site.t.5sauclgylic0": "工作室头衔颜色(仅支持英文，例如green)",
      "code8.site.t.5sauclgyllk0": "正在上传中",
      "code8.site.t.5sauclgylns0": "点击更新保存你的头像",
      "code8.site.t.5sauclgylpw0": "更新",
      "code8.site.t.5sauclgylt00": "用户信息正在加载中",
      "code8.site.t.5sauclgylv40": "当前用户已被封禁，请联系",
      "code8.site.t.5sauclgylxc0": "编辑",
      "code8.site.t.5sauclgylzc0": "保存",
      "code8.site.t.5sauclgym1c0": "最后活跃",
      "code8.site.t.5sauclgym7g0": "签到",
      "code8.site.t.5sauclgym9g0": "粉丝",
      "code8.site.t.5sauclgymbk0": "关注",
      "code8.site.t.5sauclgymds0": "获取方式：",
      "code8.site.t.5sauclgymfs0": "用户介绍",
      "code8.site.t.5sauclgymi00": "介绍",
      "code8.site.t.5sauclgymk00": "支持markdown，您可以拖动输入框右下角的三条斜线以拉大输入框",
      "code8.site.t.5sauclgymm40": "他的作品：",
      "code8.site.t.5sauclgymo80": "的作品",
      "code8.site.t.5sauclgymrs0": "当前用户还没有作品哦",
      "code8.site.t.5sauclgymtw0": "他的收藏夹：",
      "code8.site.t.5sauclgymw40": "当前用户还没有收藏夹哦",
      "code8.site.t.5sauclgymy80": "当前作品还没有发布，仅自己可见，请前往",
      "code8.site.t.5sauclgyn040": "作品信息编辑页",
      "code8.site.t.5sauclgyn240": "勾选发布，再点更新，即可发布",
      "code8.site.t.5sauclgyn480": "当前作品已被封禁，请联系",
      "code8.site.t.5sauclgyn6g0": "发布最新版",
      "code8.site.t.5sauclgyn8k0": "注：点了这个按钮后，其他人访问你的作品，才会显示现在的最新版本，否则将会显示上一次点这个按钮、或创作页中的发布、或首次发布时的版本",
      "code8.site.t.5sauclgynak0": "无权限访问此作品",
      "code8.site.t.5sauclgynd40": "代码分析",
      "code8.site.t.5sauclgynf40": "分享",
      "code8.site.t.5sauclgynh80": "作品介绍",
      "code8.site.t.5sauclgynjg0": "转到创作页",
      "code8.site.t.5sauclgynm80": "编辑作品信息",
      "code8.site.t.5sauclgynoo0": "无权限查看当前作品",
      "code8.site.t.5sauclgynqs0": "作品信息正在加载中",
      "code8.site.t.5sauclgynss0": "返回",
      "code8.site.t.5sauclgynv00": "友情链接：",
      "code8.site.t.5sauclgynww0": "将scratch作品打包成exe或html",
      "code8.site.t.5sauclgynzg0": "关闭",
      "code8.site.t.5sav9860uqs0": "创建时间：",
      "code8.site.t.FourmPost": "帖子",
      "code8.site.t.RetrievePassword": "找回密码",
      "code8.site.t.allow": "允许",
      "code8.site.t.bag": "背包",
      "code8.site.t.category": "类别",
      "code8.site.t.create": "创建",
      "code8.site.t.forum": "论坛",
      "code8.site.t.head": "头像",
      "code8.site.t.login": "登录",
      "code8.site.t.new_pw": "新密码",
      "code8.site.t.opensource": "开源",
      "code8.site.t.p1": "输对密码的所有人加入",
      "code8.site.t.p2": "所有人加入",
      "code8.site.t.p3": "输对密码并没有工作室的人加入",
      "code8.site.t.p4": "没有工作室的人加入",
      "code8.site.t.p5": "工作室头像(建议尺寸1:1)",
      "code8.site.t.p6": "的粉丝",
      "code8.site.t.p7": "的关注",
      "code8.site.t.p8": "条评论",
      "code8.site.t.price": "价格",
      "code8.site.t.publish": "发布",
      "code8.site.t.pw": "密码",
      "code8.site.t.register": "注册",
      "code8.site.t.s": "还有",
      "code8.site.t.studio": "工作室",
      "code8.site.t.timeConsuming": "耗时",
      "code8.site.t.update": "更新",
      "code8.site.t.use": "使用",
      "code8.site.t.use_position": "使用位置",
      "code8.site.t.userCenter": "个人中心",
      "code8.site.t.work": "作品",
      "code8.site.t.workcover": "作品封面图(建议尺寸1:1)",
      "code8.site.test2.5sayc8xw6bk0": "未知错误",
      "code8.site.test2.5sayc8xwa7k0": "请登录后查看",
      "code8.site.test2.5sayc8xwciw0": "你没有权限，当前作品未开源或未发布",
      "code8.site.test2.5sayc8xwcts0": "改编",
      "code8.site.test2.5sayc8xwd000": "当前作品仅支持Firefox（火狐）浏览器打开，请切换至火狐浏览器",
      "code8.site.test2.5sayc8xwd5s0": "仅支持Firefox",
      "code8.site.test2.5sayc8xwdao0": "作品加载失败",
      "code8.site.test3.5sbkhftojdo0": "回复",
      "code8.site.test3.5sbkhftokp80": "删除",
      "code8.site.test3.5sbkhftokwg0": "显示更多",
      "code8.site.test3.5sbkhftol180": "作品推荐卡",
      "code8.site.test3.5sbkhftol5c0": "作者",
      "code8.site.test3.5sbkhftolro0": "此用户暂时没有评论哦",
      "js.app.5sb6nyf9u9c0": "设置cookie",
      "js.app.5sb6nyf9uxo0": "获取信息成功",
      "js.app.5sb6nyf9v2w0": "清除cookie",
      "js.app.5sb6nyf9v680": "服务器或网络错误",
      "js.main.5sb0258vva80": "请选择图片并等待上传完毕后再继续操作",
      "js.main.5sb0258vw740": "发送成功",
      "js.main.5sb0258vwcg0": "获取评论",
      "js.main.5sb0258vwfg0": "删除成功",
      "js.main.5sb0258vwl40": "标题和正文必须大于2个字",
      "js.main.5sb0258vwpc0": "你确定要删除这个帖子吗",
      "js.main.5sb0258vwsw0": "确认使用-",
      "js.main.5sb0258vwwg0": "新手礼包",
      "js.main.5sb0258vwzo0": "初级精华作品大礼包",
      "js.main.5sb0258vx2o0": "我的主页",
      "js.main.5sb0258vx5c0": "我的作品",
      "js.main.5sb0258vx8c0": "我的工作室",
      "js.main.5sb0258vxaw0": "我的物品",
      "js.main.5sb0258vxec0": "账号设置",
      "js.main.5sb0258vxh80": "我的收藏",
      "js.main.5sb0258vxjs0": "邀请用户领金币",
      "js.main.5sb0258vxmk0": "刷新",
      "js.main.5sb0258vxpc0": "退出登录",
      "js.main.5sb0258vxrs0": "清除cookie",
      "js.main.5sb0258vxv00": "图片必须小于1MB",
      "js.main.5sb0258vy0k0": "不支持此格式的图片",
      "js.main.5sb0258vy300": "图片上传失败",
      "js.main.5sb0258vy5o0": "最早创建",
      "js.main.5sb0258vy880": "最早发布",
      "js.main.5sb0258vyac0": "最近更新",
      "js.main.5sb0258vyco0": "最近发布",
      "js.main.5sb0258vyf40": "最多点赞",
      "js.main.5sb0258vyhc0": "最多浏览",
      "js.main.5sb0258vyjs0": "最多收藏",
      "js.main.5sb0258vyls0": "最多金币",
      "js.main.5sb0258vyo40": "最新注册",
      "js.main.5sb0258vyqc0": "最早注册",
      "js.main.5sb0258vyss0": "最多成员",
      "js.main.5sb0258vyuw0": "最多作品",
      "js.main.5sb0258vyx40": "最新创建",
      "js.main.5sb0258vyzs0": "最新发布",
      "js.main.5sb0258vz200": "请输入正确的邮箱",
      "js.main.5sb0258vz4c0": "请输入6位数字验证码",
      "js.main.5sb0258vz6g0": "你确定要创建工作室吗？",
      "js.main.5sb0258vz8w0": "你确定要删除TA吗",
      "js.main.5sb0258vzb00": "你确定要退出吗",
      "js.main.5sb0258vzdc0": "此工作室禁止任何人加入",
      "js.main.5sb0258vzg00": "请输入工作室加入密码",
      "js.main.5sb0258vzik0": "请输入作品的链接或id",
      "js.main.5sb0258vzlg0": "请输入正确的链接",
      "js.main.5sb0258vznk0": "获取消息",
      "js.main.5sb0258vzpw0": "作品",
      "js.main.cy": "成员",
      "js.main.5sb0258vzs00": "你确定要删除此作品吗",
      "js.main.5sb0258vzuc0": "取消收藏成功",
      "js.main.5sb0258vzww0": "请稍等",
      "js.main.5sb0258vzzc0": "请等待作品加载完毕再进行分析",
      "js.main.5sb0258w01c0": "关注列表",
      "js.main.5sb0258w03g0": "粉丝列表",
      "js.main.5sb0258w05o0": "消息",
      "js.main.5sb0258w07o0": "登录注册",
      "js.main.5sb0258w09s0": "工作室",
      "js.main.5sb0258w0c00": "当前工作室暂时没有介绍哦",
      "js.main.5sb0258w0e00": "工作室设置",
      "js.main.5sb0258w0g40": "用户",
      "js.main.5sb0258w0ig0": "当前用户暂时没有介绍哦",
      "js.main.5sb0258w0kk0": "服务器或网络错误",
      "js.main.5sb0258w0mk0": "作品信息设置",
      "js.main.5sb0258w0ow0": "密码必须大于6位",
      "js.main.5sb0258w0s00": "纯数字密码必须大于9位",
      "js.main.5sb0258w0u00": "图片大小不能大于2MB",
      "js.main.5sb0258w0w80": "未统计",
      "js.main.5sb08wussvk0": "若你作品中包含其他人的素材或代码，请在这里注明。+",
      "js.main.5sb08wustm80": "若此作品非你原创，请使用转载声明+",
      "js.main.5sb08wustrc0": "请注明你作品的来源+",
      "js.main.5sb08wustug0": "你已获得：原创声明*1，转载声明*1，银元宝*1。+",
      "js.main.5sb08wustxg0": "你已获得：金元宝*1。+",
      "js.main.5sb08wusu180": "禁言时间+",
      "js.main.5sb08wusu400": "天",
      "js.main.5sb0drv2fxk0": "链接有效期7天，获取到此链接的人可查看此作品",
      "js.main.5sbkjtqik000": "发送",
      "js.main.5sbkjtqila00": "的收藏夹",
      "js.main.5sbkjtqilhw0": "购买",
      "js.main.5sbkjtqilmk0": "金币",
      "js.main.5sbkjtqilrk0": "室长",
      "js.main.5sbkjtqim1c0": "副室长",
      "js.main.5sbkjtqim7k0": "管理员",
      "js.main.5sbkjtqimc00": "移出工作室",
      "js.main.5sbkjtqimg80": "取消管理员",
      "js.main.5sbkjtqlr580": "设为管理员",
      "js.main.5sbkjtqls740": "取消副室长",
      "js.main.5sbkjtqlsgo0": "设为副室长",
      "js.main.5sbkjtqlsq40": "已发布",
      "js.main.5sbkjtqlsx40": "未发布",
      "js.main.5sbkjtqlt100": "继续创作",
      "js.main.5sbkjtqlt600": "删除",
      "js.main.p1": "你确定要删除此评论吗? ",
      "js.main.p2": "(你正在使用管理员权限)",
      "js.main.p3": "请先完成图形验证码",
      "js.main.p4": "说明",
      "js.scratch.5sb6i8uwwuc0": "设置当前截图为封面",
      "js.scratch.5sb6i8uwwz80": "保存",
      "js.scratch.5sb6kuv80440": "设置cookie",
      "js.scratch.5sb6kuv815c0": "获取信息成功",
      "js.scratch.5sb6kuv81ac0": "清除cookie",
      "js.scratch.5sb6kuv81dw0": "服务器或网络错误",
      "js.scratch.5sb6kuv81gs0": "正在保存封面文件",
      "js.scratch.5sb6kuv81kg0": "保存失败",
      "js.scratch.5sb6kuv81ns0": "封面保存成功",
      "js.scratch.5sb6kuv81rc0": "正在保存封面……",
      "js.scratch.5sb6kuv81w00": "自定义按钮1",
      "js.scratch.5sb6kuv81z80": "分享按钮",
      "js.scratch.5sb6kuv821w0": "保存",
      "js.scratch.5sb6kuv824w0": "正在保存作品文件……",
      "js.scratch.5sb6kuv82880": "作品保存成功",
      "js.scratch.5sb6kuv82bc0": "被迫退出",
      "js.scratch.5sb6kuv82e80": "尺寸过大",
      "js.scratch.5sb6kuv82hc0": "跳过",
      "js.scratch.5sb6kuv82nk0": "正在保存素材……",
      "js.scratch.5sb6kuv82qo0": "正在检查素材列表……",
      "js.scratch.5sb6kuv82uk0": "保存中……",
      "js.scratch.5sb6kuv82yo0": "改编中……",
      "code8.site.t.user":"用户",
      "Join_Discord":"加入discord"
    }
  },
  'en':{
    translation:{
      "code8.site.t.5sauclgyc780": "Explore",
   "code8.site.t.5sauclgyd2o0": "Forum",
   "code8.site.t.5sauclgyda00": "Sponsor code8",
   "code8.site.t.5sauclgydf40": "Creation",
   "code8.site.t.5sauclgydi00": "Download",
   "code8.site.t.5sauclgydl00": "Login/Register",
   "code8.site.t.5sauclgydpg0": "The current page does not exist",
   "code8.site.t.5sauclgydts0": "About us:",
   "code8.site.t.5sauclgydxc0": "Information Change",
   "code8.site.t.5sauclgye080": "Nickname",
   "code8.site.t.5sauclgye4k0": "Introduction",
   "code8.site.t.5sauclgye7k0": "Support writing in markdown",
   "code8.site.t.5sauclgyeas0": "Do not open the page in a new window (the access speed will be faster. After clicking to change the information, press f5 to take effect)",
   "code8.site.t.5sauclgyedg0": "Night mode (please refresh after enabling)",
   "code8.site.t.5sauclgyehs0": "Uploading...",
   "code8.site.t.5sauclgyek80": "Uploaded successfully",
   "code8.site.t.5sauclgyeow0": "Change Information",
   "code8.site.t.5sauclgyetc0": "Old Password",
   "code8.site.t.5sauclgyewk0": "New Password",
   "code8.site.t.5sauclgyezg0": "Change Password",
   "code8.site.t.5sauclgyf340": "Mobile phone number:",
   "code8.site.t.5sauclgyf7c0": "Email:",
   "code8.site.t.5sauclgyfbo0": "Publish a post",
   "code8.site.t.5sauclgyffo0": "Search",
   "code8.site.t.5sauclgyfhs0": "Post issued",
   "code8.site.t.5sauclgyfjw0": "Title",
   "code8.site.t.5sauclgyfm80": "Post content",
   "code8.site.t.5sauclgyfpc0": "Send something",
   "code8.site.t.5sauclgyfrg0": "Publish",
   "code8.site.t.5sauclgyftw0": "Cancel",
   "code8.site.t.5sauclgyfw00": "More",
   "code8.site.t.5sauclgyfyc0": "User List",
   "code8.site.t.5sauclgyg280": "Studio List",
   "code8.site.t.5sauclgyg4c0": "Send private message",
   "code8.site.t.5sauclgyg6k0": "The other party's id",
   "code8.site.t.5sauclgyg8g0": "Content",
   "code8.site.t.5sauclgygao0": "Send",
   "code8.site.t.5sauclgyges0": "My Items",
   "code8.site.t.5sauclgygh00": "Gold coins:",
   "code8.site.t.5sauclgygj40": "Gold Coin Record",
   "code8.site.t.5sauclgyglc0": "Shop",
   "code8.site.t.5sauclgygo80": "Item Information",
   "code8.site.t.5sauclgygqg0": "hour expires",
   "code8.site.t.5sauclgygsk0": "Gold Coins",
   "code8.site.t.5sauclgygv80": "Only for yourself",
   "code8.site.t.5sauclgygzc0": "use",
   "code8.site.t.5sauclgyh1k0": "Quantity",
   "code8.site.t.5sauclgyh5g0": "Buy",
   "code8.site.t.5sauclgyh8w0": "My studio:",
   "code8.site.t.5sauclgyiow0": "New Studio",
   "code8.site.t.5sauclgyiss0": "My work:",
   "code8.site.t.5sauclgyiwg0": "New work",
   "code8.site.t.5sauclgyiyk0": "Delete",
   "code8.site.t.5sauclgyj2w0": "Comment",
   "code8.site.t.5sauclgyj740": "work",
   "code8.site.t.5sauclgyj9c0": "User",
   "code8.site.t.5sauclgyjbg0": "Studio",
   "code8.site.t.5sauclgyjdg0": "Work Name",
   "code8.site.t.5sauclgyjfs0": "author id",
   "code8.site.t.5sauclgyji00": "Username",
   "code8.site.t.5sauclgyjk00": "Studio Name",
   "code8.site.t.5sauclgyjnc0": "Found for you",
   "code8.site.t.5sauclgyjps0": "Email",
   "code8.site.t.5sauclgyjt00": "Email verification code (6 digits)",
   "code8.site.t.5sauclgyjv40": "Send verification code",
   "code8.site.t.5sauclgyjx80": "Already have an account?",
   "code8.site.t.5sauclgyjzg0": "Login",
   "code8.site.t.5sauclgyk1g0": "No account?",
   "code8.site.t.5sauclgyk3k0": "Retrieve password",
   "code8.site.t.5sauclgyk5o0": "Login or registration means consent",
   "code8.site.t.5sauclgyk7s0": "Studio information is loading",
   "code8.site.t.5sauclgyk9s0": "The current studio has been banned, please contact",
   "code8.site.t.5sauclgykc40": "Administrator",
   "code8.site.t.5sauclgykec0": "Make appeal",
   "code8.site.t.5sauclgykgg0": "Edit Information",
   "code8.site.t.5sauclgykig0": "Join",
   "code8.site.t.5sauclgykks0": "Exit",
   "code8.site.t.5sauclgyko00": "Set as main room",
   "code8.site.t.5sauclgykq40": "Contributed works",
   "code8.site.t.5sauclgyks40": "Studio Introduction",
   "code8.site.t.5sauclgykuo0": "Studio works:",
   "code8.site.t.5sauclgykx40": "There is no work in the current studio",
   "code8.site.t.5sauclgykz80": "Studio members:",
   "code8.site.t.5sauclgyl180": "The current studio has no members",
   "code8.site.t.5sauclgyl380": "Please wait",
   "code8.site.t.5sauclgyl5g0": "Loading",
   "code8.site.t.5sauclgyl9o0": "Studio name",
   "code8.site.t.5sauclgylc00": "Enable Password",
   "code8.site.t.5sauclgyle80": "Add Password",
   "code8.site.t.5sauclgylg80": "Forbid anyone to join",
   "code8.site.t.5sauclgylic0": "Studio title color (only supports English, such as green)",
   "code8.site.t.5sauclgyllk0": "Uploading",
   "code8.site.t.5sauclgylns0": "Click to update to save your avatar",
   "code8.site.t.5sauclgylpw0": "Update",
   "code8.site.t.5sauclgylt00": "User information is loading",
   "code8.site.t.5sauclgylv40": "The current user has been banned, please contact",
   "code8.site.t.5sauclgylxc0": "Edit",
   "code8.site.t.5sauclgylzc0": "Save",
   "code8.site.t.5sauclgym1c0": "Last Active",
   "code8.site.t.5sauclgym7g0": "Sign in",
   "code8.site.t.5sauclgym9g0": "Followers",
   "code8.site.t.5sauclgymbk0": "Followings",
   "code8.site.t.5sauclgymds0": "Acquisition method:",
   "code8.site.t.5sauclgymfs0": "User Introduction",
   "code8.site.t.5sauclgymi00": "Introduction",
   "code8.site.t.5sauclgymk00": "Support markdown, you can drag the three slashes in the lower right corner of the input box to enlarge the input box",
   "code8.site.t.5sauclgymm40": "His works:",
   "code8.site.t.5sauclgymo80": "Works",
   "code8.site.t.5sauclgymrs0": "The current user has no works yet",
   "code8.site.t.5sauclgymtw0": "His Favorites:",
   "code8.site.t.5sauclgymw40": "The current user has no favorites yet",
   "code8.site.t.5sauclgymy80": "The current work has not been published yet, only you can see it, please go to the",
   "code8.site.t.5sauclgyn040": "Work information editing page,",
   "code8.site.t.5sauclgyn240": "Check Publish, then click Update to publish",
   "code8.site.t.5sauclgyn480": "The current work has been banned, please contact",
   "code8.site.t.5sauclgyn6g0": "Publish the latest version",
   "code8.site.t.5sauclgyn8k0": "Note: After clicking this button, the latest version will be displayed only when other people access your work, otherwise it will display the last time this button was clicked or the publication on the creation page , or the version at first release",
   "code8.site.t.5sauclgynak0": "No permission to access this work",
   "code8.site.t.5sauclgynd40": "Code Analysis",
   "code8.site.t.5sauclgynf40": "Share",
   "code8.site.t.5sauclgynh80": "Work Introduction",
   "code8.site.t.5sauclgynjg0": "Go to authoring page",
   "code8.site.t.5sauclgynm80": "Edit work information",
   "code8.site.t.5sauclgynoo0": "No permission to view current works",
   "code8.site.t.5sauclgynqs0": "Work information is loading",
   "code8.site.t.5sauclgynss0": "Return",
   "code8.site.t.5sauclgynv00": "Friendship link:",
   "code8.site.t.5sauclgynww0": "Package scratch works into exe or html",
   "code8.site.t.5sauclgynzg0": "Close",
   "code8.site.t.5sav9860uqs0": "Creation time:",
   "code8.site.t.FourmPost": "Post",
   "code8.site.t.RetrievePassword": "Retrieve Password",
   "code8.site.t.allow": "Allow",
   "code8.site.t.bag": "Backpack",
   "code8.site.t.category": "Category",
   "code8.site.t.create": "Creation time",
   "code8.site.t.forum": "Forum",
   "code8.site.t.head": "Avatar",
   "code8.site.t.login": "Login",
   "code8.site.t.new_pw": "New Password",
   "code8.site.t.opensource": "Open Source",
   "code8.site.t.p1": "Everyone who enters the correct password joins",
   "code8.site.t.p2": "Everyone joins",
   "code8.site.t.p3": "People who enter the correct password and do not have a studio join",
   "code8.site.t.p4": "People without a studio join",
   "code8.site.t.p5": "Studio avatar (recommended size 1:1)",
   "code8.site.t.p6": "Followers",
   "code8.site.t.p7": "Follow",
   "code8.site.t.p8": "Comments",
   "code8.site.t.price": "Price",
   "code8.site.t.publish": "publish time",
   "code8.site.t.pw": "Password",
   "code8.site.t.register": "Register",
   "code8.site.t.s": "And",
   "code8.site.t.studio": "Studio",
   "code8.site.t.timeConsuming": "Time Consuming",
   "code8.site.t.update": "update time",
   "code8.site.t.use": "use",
   "code8.site.t.use_position": "Use position",
   "code8.site.t.userCenter": "Personal Center",
   "code8.site.t.work": "Work",
   "code8.site.t.workcover": "Cover image of the work (recommended size 1:1)",
   "code8.site.test2.5sayc8xw6bk0": "Unknown error",
   "code8.site.test2.5sayc8xwa7k0": "Please login to view",
   "code8.site.test2.5sayc8xwciw0": "You do not have permission, the current work is not open source or published",
   "code8.site.test2.5sayc8xwcts0": "Adapted",
   "code8.site.test2.5sayc8xwd000": "The current work only supports Firefox (Firefox) browser to open, please switch to Firefox browser",
   "code8.site.test2.5sayc8xwd5s0": "Firefox only",
   "code8.site.test2.5sayc8xwdao0": "Failed to load the work",
   "code8.site.test3.5sbkhftojdo0": "Reply",
   "code8.site.test3.5sbkhftokp80": "Delete",
   "code8.site.test3.5sbkhftokwg0": "Show more",
   "code8.site.test3.5sbkhftol180": "Work recommendation card",
   "code8.site.test3.5sbkhftol5c0": "Author",
   "code8.site.test3.5sbkhftolro0": "This user has no comments yet",
   "js.app.5sb6nyf9u9c0": "Set cookie",
   "js.app.5sb6nyf9uxo0": "Get information successfully",
   "js.app.5sb6nyf9v2w0": "Clear cookies",
   "js.app.5sb6nyf9v680": "Server or network error",
   "js.main.5sb0258vva80": "Please select a picture and wait for the upload to complete before proceeding",
   "js.main.5sb0258vw740": "Sent successfully",
   "js.main.5sb0258vwcg0": "Get comments",
   "js.main.5sb0258vwfg0": "Deleted successfully",
   "js.main.5sb0258vwl40": "The title and body must be greater than 2 characters",
   "js.main.5sb0258vwpc0": "Are you sure you want to delete this post",
   "js.main.5sb0258vwsw0": "Confirm use-",
   "js.main.5sb0258vwwg0": "Newbie Pack",
   "js.main.5sb0258vwzo0": "Gift Pack of Primary Essence Works",
   "js.main.5sb0258vx2o0": "My homepage",
   "js.main.5sb0258vx5c0": "My work",
   "js.main.5sb0258vx8c0": "My Studio",
   "js.main.5sb0258vxaw0": "My Items",
   "js.main.5sb0258vxec0": "Account Settings",
   "js.main.5sb0258vxh80": "My Favorites",
   "js.main.5sb0258vxjs0": "Invite users to receive coins",
   "js.main.5sb0258vxmk0": "Refresh",
   "js.main.5sb0258vxpc0": "Logout",
   "js.main.5sb0258vxrs0": "Clear cookies",
   "js.main.5sb0258vxv00": "Image must be smaller than 1MB",
   "js.main.5sb0258vy0k0": "Images in this format are not supported",
   "js.main.5sb0258vy300": "Image upload failed",
   "js.main.5sb0258vy5o0": "Oldest Created",
   "js.main.5sb0258vy880": "Oldest release",
   "js.main.5sb0258vyac0": "Recently updated",
   "js.main.5sb0258vyco0": "Recently Released",
   "js.main.5sb0258vyf40": "Most likes",
   "js.main.5sb0258vyhc0": "Most Viewed",
   "js.main.5sb0258vyjs0": "Most Favorites",
   "js.main.5sb0258vyls0": "Most coins",
   "js.main.5sb0258vyo40": "Latest Registration",
   "js.main.5sb0258vyqc0": "Earliest Registration",
   "js.main.5sb0258vyss0": "Most Members",
   "js.main.5sb0258vyuw0": "Most works",
   "js.main.5sb0258vyx40": "Newly Created",
   "js.main.5sb0258vyzs0": "Latest release",
   "js.main.5sb0258vz200": "please enter your vaild email",
   "js.main.5sb0258vz4c0": "Please enter a 6-digit verification code",
   "js.main.5sb0258vz6g0": "Are you sure you want to create a studio?",
   "js.main.5sb0258vz8w0": "Are you sure you want to delete TA",
   "js.main.5sb0258vzb00": "Are you sure you want to exit?",
   "js.main.5sb0258vzdc0": "No one is allowed to join this workshop",
   "js.main.5sb0258vzg00": "Please enter the password to join the studio",
   "js.main.5sb0258vzik0": "Please enter the link or id of the work",
   "js.main.5sb0258vzlg0": "Please enter the correct link",
   "js.main.5sb0258vznk0": "Get Message",
   "js.main.5sb0258vzpw0": "Work",
   "js.main.cy": "Members",
   "js.main.5sb0258vzs00": "Are you sure you want to delete this work",
   "js.main.5sb0258vzuc0": "Cancel favorite successfully",
   "js.main.5sb0258vzww0": "Please wait a moment",
   "js.main.5sb0258vzzc0": "Please wait until the work is loaded before analyzing",
   "js.main.5sb0258w01c0": "Watchlist",
   "js.main.5sb0258w03g0": "Fan list",
   "js.main.5sb0258w05o0": "Message",
   "js.main.5sb0258w07o0": "Login Registration",
   "js.main.5sb0258w09s0": "Studio",
   "js.main.5sb0258w0c00": "There is no introduction for the current studio",
   "js.main.5sb0258w0e00": "Studio Settings",
   "js.main.5sb0258w0g40": "User",
   "js.main.5sb0258w0ig0": "There is no introduction for the current user",
   "js.main.5sb0258w0kk0": "Server or network error",
   "js.main.5sb0258w0mk0": "Work Information Settings",
   "js.main.5sb0258w0ow0": "The password must be greater than 6 characters",
   "js.main.5sb0258w0s00": "Pure numeric password must be greater than 9 digits",
   "js.main.5sb0258w0u00": "The image size cannot exceed 2MB",
   "js.main.5sb0258w0w80": "Not counted",
   "js.main.5sb08wussvk0": "If your work contains other people's materials or codes, please indicate here.+",
   "js.main.5sb08wustm80": "If this work is not original by you, please use the reprint statement+",
   "js.main.5sb08wustrc0": "Please indicate the source of your work+",
   "js.main.5sb08wustug0": "You have obtained: Original Statement*1, Reprinted Statement*1, Silver Ingot*1.+",
   "js.main.5sb08wustxg0": "You have obtained: Gold Ingot*1.+",
   "js.main.5sb08wusu180": "Mute time+",
   "js.main.5sb08wusu400": "day",
   "js.main.5sb0drv2fxk0": "The link is valid for 7 days, people who get this link can view this work",
   "js.main.5sbkjtqik000": "Send",
   "js.main.5sbkjtqila00": "Favorites",
   "js.main.5sbkjtqilhw0": "Buy",
   "js.main.5sbkjtqilmk0": "Gold Coins",
   "js.main.5sbkjtqilrk0": "Chairman",
   "js.main.5sbkjtqim1c0": "Deputy Chief",
   "js.main.5sbkjtqim7k0": "Administrator",
   "js.main.5sbkjtqimc00": "Move out of workshop",
   "js.main.5sbkjtqimg80": "Cancel Administrator",
   "js.main.5sbkjtqlr580": "Set as administrator",
   "js.main.5sbkjtqls740": "Cancel Deputy Head",
   "js.main.5sbkjtqlsgo0": "Set as Deputy Chief",
   "js.main.5sbkjtqlsq40": "Published",
   "js.main.5sbkjtqlsx40": "Unpublished",
   "js.main.5sbkjtqlt100": "Continue to create",
   "js.main.5sbkjtqlt600": "Delete",
   "js.main.p1": "Are you sure you want to delete this comment?",
   "js.main.p2": "(You are using administrator privileges)",
   "js.main.p3": "Please complete the graphic verification code first",
   "js.main.p4": "Description",
   "js.scratch.5sb6i8uwwuc0": "Set the current screenshot as the cover",
   "js.scratch.5sb6i8uwwz80": "Save",
   "js.scratch.5sb6kuv80440": "Set cookie",
   "js.scratch.5sb6kuv815c0": "Get information successfully",
   "js.scratch.5sb6kuv81ac0": "Clear cookies",
   "js.scratch.5sb6kuv81dw0": "Server or network error",
   "js.scratch.5sb6kuv81gs0": "Saving cover file",
   "js.scratch.5sb6kuv81kg0": "Failed to save",
   "js.scratch.5sb6kuv81ns0": "The cover was saved successfully",
   "js.scratch.5sb6kuv81rc0": "Saving cover...",
   "js.scratch.5sb6kuv81w00": "Custom button 1",
   "js.scratch.5sb6kuv81z80": "Share button",
   "js.scratch.5sb6kuv821w0": "Save",
   "js.scratch.5sb6kuv824w0": "Saving work file...",
   "js.scratch.5sb6kuv82880": "Work saved successfully",
   "js.scratch.5sb6kuv82bc0": "Forced to quit",
   "js.scratch.5sb6kuv82e80": "Size too large",
   "js.scratch.5sb6kuv82hc0": "Skip",
   "js.scratch.5sb6kuv82nk0": "Saving material...",
   "js.scratch.5sb6kuv82qo0": "Checking material list...",
   "js.scratch.5sb6kuv82uk0": "Saving...",
   "js.scratch.5sb6kuv82yo0": "Adapting...",
   "code8.site.t.user":"user",
   "Join_Discord":"Join Discord"
    }
  },
  'zh_tw':{
    translation:{
      "code8.site.t.5sauclgyc780": "發現作品",
      "code8.site.t.5sauclgyd2o0": "論壇",
      "code8.site.t.5sauclgyda00": "贊助code8",
      "code8.site.t.5sauclgydf40": "創作",
      "code8.site.t.5sauclgydi00": "下載",
      "code8.site.t.5sauclgydl00": "登錄/註冊",
      "code8.site.t.5sauclgydpg0": "當前頁面不存在",
      "code8.site.t.5sauclgydts0": "關於我們：",
      "code8.site.t.5sauclgydxc0": "信息更改",
      "code8.site.t.5sauclgye080": "暱稱",
      "code8.site.t.5sauclgye4k0": "個人介紹",
      "code8.site.t.5sauclgye7k0": "支持使用markdown編寫",
      "code8.site.t.5sauclgyeas0": "不在新窗口打開頁面(訪問速度會更快。點更改信息後，按下f5生效)",
      "code8.site.t.5sauclgyedg0": "夜間模式(開啟後請刷新)",
      "code8.site.t.5sauclgyehs0": "正在上傳中……",
      "code8.site.t.5sauclgyek80": "上傳成功",
      "code8.site.t.5sauclgyeow0": "更改信息",
      "code8.site.t.5sauclgyetc0": "舊密碼",
      "code8.site.t.5sauclgyewk0": "新密碼",
      "code8.site.t.5sauclgyezg0": "更改密碼",
      "code8.site.t.5sauclgyf340": "手機號：",
      "code8.site.t.5sauclgyf7c0": "郵箱：",
      "code8.site.t.5sauclgyfbo0": "發布帖子",
      "code8.site.t.5sauclgyffo0": "搜索",
      "code8.site.t.5sauclgyfhs0": "帖子發出",
      "code8.site.t.5sauclgyfjw0": "標題",
      "code8.site.t.5sauclgyfm80": "帖子內容",
      "code8.site.t.5sauclgyfpc0": "發點什麼吧",
      "code8.site.t.5sauclgyfrg0": "發布",
      "code8.site.t.5sauclgyftw0": "取消",
      "code8.site.t.5sauclgyfw00": "更多",
      "code8.site.t.5sauclgyfyc0": "用戶榜",
      "code8.site.t.5sauclgyg280": "工作室榜",
      "code8.site.t.5sauclgyg4c0": "發送私信",
      "code8.site.t.5sauclgyg6k0": "對方id",
      "code8.site.t.5sauclgyg8g0": "內容",
      "code8.site.t.5sauclgygao0": "發送",
      "code8.site.t.5sauclgyges0": "我的物品",
      "code8.site.t.5sauclgygh00": "金幣：",
      "code8.site.t.5sauclgygj40": "金幣記錄",
      "code8.site.t.5sauclgyglc0": "商店",
      "code8.site.t.5sauclgygo80": "物品信息",
      "code8.site.t.5sauclgygqg0": "小時失效",
      "code8.site.t.5sauclgygsk0": "金幣",
      "code8.site.t.5sauclgygv80": "僅可對自己使用",
      "code8.site.t.5sauclgygzc0": "使用",
      "code8.site.t.5sauclgyh1k0": "數量",
      "code8.site.t.5sauclgyh5g0": "購買",
      "code8.site.t.5sauclgyh8w0": "我的工作室：",
      "code8.site.t.5sauclgyiow0": "新建工作室",
      "code8.site.t.5sauclgyiss0": "我的作品：",
      "code8.site.t.5sauclgyiwg0": "新建作品",
      "code8.site.t.5sauclgyiyk0": "刪除",
      "code8.site.t.5sauclgyj2w0": "評論",
      "code8.site.t.5sauclgyj740": "作品",
      "code8.site.t.5sauclgyj9c0": "用戶",
      "code8.site.t.5sauclgyjbg0": "工作室",
      "code8.site.t.5sauclgyjdg0": "作品名",
      "code8.site.t.5sauclgyjfs0": "作者id",
      "code8.site.t.5sauclgyji00": "用戶名",
      "code8.site.t.5sauclgyjk00": "工作室名稱",
      "code8.site.t.5sauclgyjnc0": "為你找到",
      "code8.site.t.5sauclgyjps0": "郵箱",
      "code8.site.t.5sauclgyjt00": "郵件驗證碼(6位)",
      "code8.site.t.5sauclgyjv40": "發送驗證碼",
      "code8.site.t.5sauclgyjx80": "已有賬號？",
      "code8.site.t.5sauclgyjzg0": "登錄",
      "code8.site.t.5sauclgyk1g0": "沒有賬號？",
      "code8.site.t.5sauclgyk3k0": "找回密碼",
      "code8.site.t.5sauclgyk5o0": "登錄或註冊即代表同意",
      "code8.site.t.5sauclgyk7s0": "工作室信息正在加載中",
      "code8.site.t.5sauclgyk9s0": "當前工作室已被封禁，請聯繫",
      "code8.site.t.5sauclgykc40": "管理員",
      "code8.site.t.5sauclgykec0": "進行申訴",
      "code8.site.t.5sauclgykgg0": "編輯信息",
      "code8.site.t.5sauclgykig0": "加入",
      "code8.site.t.5sauclgykks0": "退出",
      "code8.site.t.5sauclgyko00": "設為主室",
      "code8.site.t.5sauclgykq40": "投稿作品",
      "code8.site.t.5sauclgyks40": "工作室介紹",
      "code8.site.t.5sauclgykuo0": "工作室作品：",
      "code8.site.t.5sauclgykx40": "當前工作室無作品",
      "code8.site.t.5sauclgykz80": "工作室成員：",
      "code8.site.t.5sauclgyl180": "當前工作室無成員",
      "code8.site.t.5sauclgyl380": "請等待",
      "code8.site.t.5sauclgyl5g0": "正在加載中",
      "code8.site.t.5sauclgyl9o0": "工作室名",
      "code8.site.t.5sauclgylc00": "啟用密碼",
      "code8.site.t.5sauclgyle80": "加入密碼",
      "code8.site.t.5sauclgylg80": "禁止任何人加入",
      "code8.site.t.5sauclgylic0": "工作室頭銜顏色(僅支持英文，例如green)",
      "code8.site.t.5sauclgyllk0": "正在上傳中",
      "code8.site.t.5sauclgylns0": "點擊更新保存你的頭像",
      "code8.site.t.5sauclgylpw0": "更新",
      "code8.site.t.5sauclgylt00": "用戶信息正在加載中",
      "code8.site.t.5sauclgylv40": "當前用戶已被封禁，請聯繫",
      "code8.site.t.5sauclgylxc0": "編輯",
      "code8.site.t.5sauclgylzc0": "保存",
      "code8.site.t.5sauclgym1c0": "最後活躍",
      "code8.site.t.5sauclgym7g0": "簽到",
      "code8.site.t.5sauclgym9g0": "粉絲",
      "code8.site.t.5sauclgymbk0": "關注",
      "code8.site.t.5sauclgymds0": "獲取方式：",
      "code8.site.t.5sauclgymfs0": "用戶介紹",
      "code8.site.t.5sauclgymi00": "介紹",
      "code8.site.t.5sauclgymk00": "支持markdown，您可以拖動輸入框右下角的三條斜線以拉大輸入框",
      "code8.site.t.5sauclgymm40": "他的作品：",
      "code8.site.t.5sauclgymo80": "的作品",
      "code8.site.t.5sauclgymrs0": "當前用戶還沒有作品哦",
      "code8.site.t.5sauclgymtw0": "他的收藏夾：",
      "code8.site.t.5sauclgymw40": "當前用戶還沒有收藏夾哦",
      "code8.site.t.5sauclgymy80": "當前作品還沒有發布，僅自己可見，請前往",
      "code8.site.t.5sauclgyn040": "作品信息編輯頁","code8.site.t.5sauclgyn240": "勾選發布，再點更新，即可發布",
      "code8.site.t.5sauclgyn480": "當前作品已被封禁，請聯繫",
      "code8.site.t.5sauclgyn6g0": "發布最新版",
      "code8.site.t.5sauclgyn8k0": "注：點了這個按鈕後，其他人訪問你的作品，才會顯示現在的最新版本，否則將會顯示上一次點這個按鈕、或創作頁中的發布、或首次發佈時的版本",
      "code8.site.t.5sauclgynak0": "無權限訪問此作品",
      "code8.site.t.5sauclgynd40": "代碼分析",
      "code8.site.t.5sauclgynf40": "分享",
      "code8.site.t.5sauclgynh80": "作品介紹",
      "code8.site.t.5sauclgynjg0": "轉到創作頁",
      "code8.site.t.5sauclgynm80": "編輯作品信息",
      "code8.site.t.5sauclgynoo0": "無權限查看當前作品",
      "code8.site.t.5sauclgynqs0": "作品信息正在加載中",
      "code8.site.t.5sauclgynss0": "返回",
      "code8.site.t.5sauclgynv00": "友情鏈接：",
      "code8.site.t.5sauclgynww0": "將scratch作品打包成exe或html",
      "code8.site.t.5sauclgynzg0": "關閉",
      "code8.site.t.5sav9860uqs0": "創建時間：",
      "code8.site.t.FourmPost": "帖子",
      "code8.site.t.RetrievePassword": "找回密碼",
      "code8.site.t.allow": "允許",
      "code8.site.t.bag": "背包",
      "code8.site.t.category": "類別",
      "code8.site.t.create": "創建",
      "code8.site.t.forum": "論壇",
      "code8.site.t.head": "頭像",
      "code8.site.t.login": "登錄",
      "code8.site.t.new_pw": "新密碼",
      "code8.site.t.opensource": "開源",
      "code8.site.t.p1": "輸對密碼的所有人加入",
      "code8.site.t.p2": "所有人加入",
      "code8.site.t.p3": "輸對密碼並沒有工作室的人加入",
      "code8.site.t.p4": "沒有工作室的人加入",
      "code8.site.t.p5": "工作室頭像(建議尺寸1:1)",
      "code8.site.t.p6": "的粉絲",
      "code8.site.t.p7": "的關注",
      "code8.site.t.p8": "條評論",
      "code8.site.t.price": "價格",
      "code8.site.t.publish": "發布",
      "code8.site.t.pw": "密碼",
      "code8.site.t.register": "註冊",
      "code8.site.t.s": "還有",
      "code8.site.t.studio": "工作室",
      "code8.site.t.timeConsuming": "耗時",
      "code8.site.t.update": "更新",
      "code8.site.t.use": "使用",
      "code8.site.t.use_position": "使用位置",
      "code8.site.t.userCenter": "個人中心",
      "code8.site.t.work": "作品",
      "code8.site.t.workcover": "作品封面圖(建議尺寸1:1)",
      "code8.site.test2.5sayc8xw6bk0": "未知錯誤",
      "code8.site.test2.5sayc8xwa7k0": "請登錄後查看",
      "code8.site.test2.5sayc8xwciw0": "你沒有權限，當前作品未開源或未發布",
      "code8.site.test2.5sayc8xwcts0": "改編",
      "code8.site.test2.5sayc8xwd000": "當前作品僅支持Firefox（火狐）瀏覽器打開，請切換至火狐瀏覽器",
      "code8.site.test2.5sayc8xwd5s0": "僅支持Firefox",
      "code8.site.test2.5sayc8xwdao0": "作品加載失敗",
      "code8.site.test3.5sbkhftojdo0": "回复",
      "code8.site.test3.5sbkhftokp80": "刪除",
      "code8.site.test3.5sbkhftokwg0": "顯示更多",
      "code8.site.test3.5sbkhftol180": "作品推薦卡",
      "code8.site.test3.5sbkhftol5c0": "作者",
      "code8.site.test3.5sbkhftolro0": "此用戶暫時沒有評論哦",
      "js.app.5sb6nyf9u9c0": "設置cookie",
      "js.app.5sb6nyf9uxo0": "獲取信息成功",
      "js.app.5sb6nyf9v2w0": "清除cookie",
      "js.app.5sb6nyf9v680": "服務器或網絡錯誤",
      "js.main.5sb0258vva80": "請選擇圖片並等待上傳完畢後再繼續操作",
      "js.main.5sb0258vw740": "發送成功",
      "js.main.5sb0258vwcg0": "獲取評論",
      "js.main.5sb0258vwfg0": "刪除成功",
      "js.main.5sb0258vwl40": "標題和正文必須大於2個字",
      "js.main.5sb0258vwpc0": "你確定要刪除這個帖子嗎",
      "js.main.5sb0258vwsw0": "確認使用-",
      "js.main.5sb0258vwwg0": "新手禮包",
      "js.main.5sb0258vwzo0": "初級精華作品大禮包",
      "js.main.5sb0258vx2o0": "我的主頁",
      "js.main.5sb0258vx5c0": "我的作品",
      "js.main.5sb0258vx8c0": "我的工作室",
      "js.main.5sb0258vxaw0": "我的物品",
      "js.main.5sb0258vxec0": "賬號設置",
      "js.main.5sb0258vxh80": "我的收藏",
      "js.main.5sb0258vxjs0": "邀請用戶領金幣",
      "js.main.5sb0258vxmk0": "刷新",
      "js.main.5sb0258vxpc0": "退出登錄",
      "js.main.5sb0258vxrs0": "清除cookie",
      "js.main.5sb0258vxv00": "圖片必須小於1MB",
      "js.main.5sb0258vy0k0": "不支持此格式的圖片",
      "js.main.5sb0258vy300": "圖片上傳失敗",
      "js.main.5sb0258vy5o0": "最早創建",
      "js.main.5sb0258vy880": "最早發布",
      "js.main.5sb0258vyac0": "最近更新",
      "js.main.5sb0258vyco0": "最近發布",
      "js.main.5sb0258vyf40": "最多點贊",
      "js.main.5sb0258vyhc0": "最多瀏覽",
      "js.main.5sb0258vyjs0": "最多收藏",
      "js.main.5sb0258vyls0": "最多金幣",
      "js.main.5sb0258vyo40": "最新註冊",
      "js.main.5sb0258vyqc0": "最早註冊",
      "js.main.5sb0258vyss0": "最多成員",
      "js.main.5sb0258vyuw0": "最多作品",
      "js.main.5sb0258vyx40": "最新創建",
      "js.main.5sb0258vyzs0": "最新發布",
      "js.main.5sb0258vz200": "請輸入正確的郵箱",
      "js.main.5sb0258vz4c0": "請輸入6位數字驗證碼",
      "js.main.5sb0258vz6g0": "你確定要創建工作室嗎？",
      "js.main.5sb0258vz8w0": "你確定要刪除TA嗎",
      "js.main.5sb0258vzb00": "你確定要退出嗎",
      "js.main.5sb0258vzdc0": "此工作室禁止任何人加入",
      "js.main.5sb0258vzg00": "請輸入工作室加入密碼",
      "js.main.5sb0258vzik0": "請輸入作品的鏈接或id",
      "js.main.5sb0258vzlg0": "請輸入正確的鏈接",
      "js.main.5sb0258vznk0": "獲取消息",
      "js.main.5sb0258vzpw0": "作品",
      "js.main.cy": "成員",
      "js.main.5sb0258vzs00": "你確定要刪除此作品嗎",
      "js.main.5sb0258vzuc0": "取消收藏成功",
      "js.main.5sb0258vzww0": "請稍等",
      "js.main.5sb0258vzzc0": "請等待作品加載完畢再進行分析",
      "js.main.5sb0258w01c0": "關注列表",
      "js.main.5sb0258w03g0": "粉絲列表",
      "js.main.5sb0258w05o0": "消息",
      "js.main.5sb0258w07o0": "登錄註冊",
      "js.main.5sb0258w09s0": "工作室",
      "js.main.5sb0258w0c00": "當前工作室暫時沒有介紹哦",
      "js.main.5sb0258w0e00": "工作室設置",
      "js.main.5sb0258w0g40": "用戶",
      "js.main.5sb0258w0ig0": "當前用戶暫時沒有介紹哦",
      "js.main.5sb0258w0kk0": "服務器或網絡錯誤",
      "js.main.5sb0258w0mk0": "作品信息設置",
      "js.main.5sb0258w0ow0": "密碼必須大於6位",
      "js.main.5sb0258w0s00": "純數字密碼必須大於9位",
      "js.main.5sb0258w0u00": "圖片大小不能大於2MB",
      "js.main.5sb0258w0w80": "未統計",
      "js.main.5sb08wussvk0": "若你作品中包含其他人的素材或代碼，請在這裡註明。+",
      "js.main.5sb08wustm80": "若此作品非你原創，請使用轉載聲明+",
      "js.main.5sb08wustrc0": "請註明你作品的來源+",
      "js.main.5sb08wustug0": "你已獲得：原創聲明*1，轉載聲明*1，銀元寶*1。+",
      "js.main.5sb08wustxg0": "你已獲得：金元寶*1。+",
      "js.main.5sb08wusu180": "禁言時間+",
      "js.main.5sb08wusu400": "天",
      "js.main.5sb0drv2fxk0": "鏈接有效期7天，獲取到此鏈接的人可查看此作品",
      "js.main.5sbkjtqik000": "發送",
      "js.main.5sbkjtqila00": "的收藏夾",
      "js.main.5sbkjtqilhw0": "購買",
      "js.main.5sbkjtqilmk0": "金幣",
      "js.main.5sbkjtqilrk0": "室長",
      "js.main.5sbkjtqim1c0": "副室長",
      "js.main.5sbkjtqim7k0": "管理員",
      "js.main.5sbkjtqimc00": "移出工作室",
      "js.main.5sbkjtqimg80": "取消管理員",
      "js.main.5sbkjtqlr580": "設為管理員",
      "js.main.5sbkjtqls740": "取消副室長",
      "js.main.5sbkjtqlsgo0": "設為副室長",
      "js.main.5sbkjtqlsq40": "已發布",
      "js.main.5sbkjtqlsx40": "未發布",
      "js.main.5sbkjtqlt100": "繼續創作",
      "js.main.5sbkjtqlt600": "刪除",
      "js.main.p1": "你確定要刪除此評論嗎? ",
      "js.main.p2": "(你正在使用管理員權限)",
      "js.main.p3": "請先完成圖形驗證碼",
      "js.main.p4": "說明",
      "js.scratch.5sb6i8uwwuc0": "設置當前截圖為封面",
      "js.scratch.5sb6i8uwwz80": "保存",
      "js.scratch.5sb6kuv80440": "設置cookie",
      "js.scratch.5sb6kuv815c0": "獲取信息成功",
      "js.scratch.5sb6kuv81ac0": "清除cookie",
      "js.scratch.5sb6kuv81dw0": "服務器或網絡錯誤",
      "js.scratch.5sb6kuv81gs0": "正在保存封面文件",
      "js.scratch.5sb6kuv81kg0": "保存失敗",
      "js.scratch.5sb6kuv81ns0": "封面保存成功",
      "js.scratch.5sb6kuv81rc0": "正在保存封面……",
      "js.scratch.5sb6kuv81w00": "自定義按鈕1",
      "js.scratch.5sb6kuv81z80": "分享按鈕",
      "js.scratch.5sb6kuv821w0": "保存",
      "js.scratch.5sb6kuv824w0": "正在保存作品文件……",
      "js.scratch.5sb6kuv82880": "作品保存成功",
      "js.scratch.5sb6kuv82bc0": "被迫退出",
      "js.scratch.5sb6kuv82e80": "尺寸過大",
      "js.scratch.5sb6kuv82hc0": "跳過",
      "js.scratch.5sb6kuv82nk0": "正在保存素材……",
      "js.scratch.5sb6kuv82qo0": "正在檢查素材列表……",
      "js.scratch.5sb6kuv82uk0": "保存中……",
      "js.scratch.5sb6kuv82yo0": "改編中……",
      "code8.site.t.user":"用戶",
      "Join_Discord":"加入discord"
    }
  }
}
let language=getCookie('language') || navigator.language.toLocaleLowerCase().replace('-','_')
let m2=Object.keys(msg),ff;
if(m2.includes(language)) window.language2=language
else if(m2.includes(language.split('_')[0])) window.language2=language.split('_')[0]
else for(let i=0;i<m2.length;i++){
  if(m2[i].split('_')[0]==language.split('_')[0]) {
    window.language2=m2[i];
    break;
  }
}
if(!window.language2){
  window.language2='en'
}
// if(!window.i18next)window.i18next=top.i18next;
i18next.init({
  lng:window.language2,
  resources:msg
})
window.$t=i18next.t
function getQueryString(name) {
    let reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)", "i");
    if(window.location.hash.indexOf("#") < 0) return null;
    let r = window.location.hash.split("#")[1].match(reg); 　　
    if (r != null) return decodeURIComponent(r[2]); 
　　    return null; 
  }
  function setCookie(cname, cvalue, exdays) {
    console.log(window.$t('js.app.5sb6nyf9u9c0'))
    var d = new Date();
    d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
    var expires = "expires=" + d.toGMTString()+(1 || location.host=='127.0.0.1:5500'?'  path=/;':'  domain=.40code.com; path=/;');
    if(exdays<0){
      var expires = "expires=" + d.toGMTString()+('  path=/;');
      document.cookie = cname + "=" + cvalue + "; " + expires;
      var expires = "expires=" + d.toGMTString()+(' domain=.40code.com; path=/;');
      document.cookie = cname + "=" + cvalue + "; " + expires;
    }
    document.cookie = cname + "=" + cvalue + "; " + expires;
  }
  function getCookie(cname) {
    
    var name = cname + "=";
    var ca = document.cookie.split(';');
    for (var i = 0; i < ca.length; i++) {
      var c = ca[i].trim();
      if (c.indexOf(name) == 0){
        let d=c.substring(name.length, c.length);
        if(cname=='token'){
          try {
            v.$data.token=d
          } catch (error) {}
        }
        return d
      } 
    }
    return "";
  }
  function getuserinfo() {
    get({
      url: 'user/myinfo'
    }, function (d) {
      userdetail=d.data;
      console.log(window.$t('js.app.5sb6nyf9uxo0'),d)
      if((typeof v) !== "undefined"){
        v.$data.detail = d.data;
        // qh('index')
      }
        
    //   $('#n-input')[0].value=d.data.nickname
      
    })
  }
  function getuserinfosync() {
    return new Promise(function(reslove){
        get({
            url: 'user/myinfo'
          }, function (d) {
            userdetail=d.data;
            console.log(window.$t('js.app.5sb6nyf9uxo0'),d)
            if((typeof v) !== "undefined") {
                v.$data.detail = d.data;
                // qh('index')
            }
            reslove(userdetail)
          })
    })
  }
  function getworkinfosync(id) {
    return new Promise(function(reslove){
        get({
            url: 'work/info',
            data:{id:id}
          }, function (d) {
            reslove(d.data)
          })
    })
  }
        function get(d, n, eee, method) {
            let d2 = d.data;
            if(typeof d==='string'){
              d={url:d}
            }
            if (!d2) d2 = {};
            if (d.p) {
                if (waitRequest[d.p]) return;
                waitRequest[d.p] = 1;
            }
            d2.token = getCookie('token');
            $.ajax({
                url: apihost + d.url,
                data: d2,
                type: method || 'get',
                // headers: { "Authorization": getCookie('token') },
                headers: { 'onreferer': location.pathname, 'href': location.href,'lng':window.language2 },
                success: function (f) {
                    console.log(f)
                    if (f.redirect) {
                        location.href = f.redirect;
                        return;
                    }
                    if (f.cz == 'exit') {
                        document.cookie = "token=; expires=Thu, 01 Jan 1970 00:00:00 GMT";
                        document.cookie = 'token=0; expires=Thu, 01 Jan 1970 00:00:00 GMT; domain=.40code.com; path=/;';document.cookie = 'token=0; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/;';
                        console.log(window.$t('js.app.5sb6nyf9v2w0'))
                    }
                    d.p && (delete waitRequest[d.p])
                    n && n(f)
                },
                error: function (e) {
                    d.p && (delete waitRequest[d.p])
                    console.log(e)
                    if (eee)
                        eee(e)
                    else
                        alert(e && e.responseJSON && (e.responseJSON.msg || e.responseJSON.errmsg) || window.$t('js.app.5sb6nyf9v680'))
                    if (e.responseJSON.redirect) {
                        location.href = e.responseJSON.redirect;
                        return;
                    }
                }
            })
        }
        function post(d, n, eee, method) {
            let d2 = d.data;
            if (d.p) {
                if (waitRequest[d.p]) return;
                waitRequest[d.p] = 1;
            }
            if (!d2) d2 = {};
            $.ajax({
                url: apihost + d.url + '?token=' + getCookie('token'),
                data: JSON.stringify(d2),
                type: method || 'post',
                contentType: 'application/json',
                headers: { 'onreferer': location.pathname, 'href': location.href, 'lng':window.language2 },
                success: function (f) {
                    console.log(f)
                    d.p && (delete waitRequest[d.p])
                    if (f.msg || f.errmsg) {
                        alert(f.msg || f.errmsg)
                    }
                    if (f.cz == 'exit') {
                        document.cookie = "token=; expires=Thu, 01 Jan 1970 00:00:00 GMT";
                        console.log(window.$t('js.app.5sb6nyf9v2w0'))
                    }
                    if (f.redirect) {
                        location.href = f.redirect;
                        return;
                    }
                    n && n(f)
                },
                error: function (e) {
                    d.p && (delete waitRequest[d.p])
                    console.log(e)
                    if (eee) eee(e)
                    else alert(e && e.responseJSON && (e.responseJSON.msg || e.responseJSON.errmsg) || window.$t('js.app.5sb6nyf9v680'))
                    if (e.responseJSON.redirect) {
                        location.href = e.responseJSON.redirect;
                        return;
                    }
                }
            })
        }

  if(getQueryString('i')){
    setCookie('i',getQueryString('i'),3);
  }
  var apihost = "https://api.code8.site/api/",
  mianhost="http://127.0.0.1:5500",
  scratchhost="https://40code-cdn.zq990.com";
